### PR TITLE
fixed and finish sponsor block

### PR DESCRIPTION
**Pull request by HeIIow2**
### New default representation of HTTPerrors

Here is one example.

```
sponsorblock.errors.NotFoundException: 
Not Found: 404 Not Found - Not Found
https://sponsor.ajay.app/api/skipSegments/?category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=preview&category=music_offtopic&category=poi_highlight&category=filler&service=YouTube&videoID=SULFl39UjgY https://sponsor.ajay.app/api/skipSegments/?category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=preview&category=music_offtopic&category=poi_highlight&category=filler&service=YouTube&videoID=SULFl39UjgY
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Connection: keep-alive
Referer: https://sponsor.ajay.app
Content-Type: application/json
b'Not Found'
```

### Removed some code redundancy

I removed some duplicated code, that raises exceptions based on the status code of requests, and put it in a function.

## ✅ Checks

- [x] My pull request adheres to the code style of this project if any
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed if any

## ℹ Additional Information

The code the function replaced was not always the same. Some status codes would at some points in the program throw `UnexpectedException`, and not a specific exception. Now ofc there is an argument to be made for this, but the code stays way simpler if you just always throw the specific exceptions, and in my opinion the change in functionality is negledable.

Thank you soooooo much for making it so easy to use this api. <33333

### CODE REVIEW

**Comment by wasi-master** [comment]
Thank you!

**Comment by HeIIow2** [comment]
> Thank you!

I hope you don't mind me asking, but why haven't you merged it yet?

:3

**Comment by wasi-master** [comment]
> > Thank you!
> 
> I hope you don't mind me asking, but why haven't you merged it yet?
> 
> :3

Sorry I was busy with something else 🙃

**Comment by wasi-master** [comment]
Merged and uploaded to PyPI as version 0.2.3

https://pypi.org/project/sponsorblock.py/0.2.3/

**Pull request merged**
