### PR TITLE
Send request as json request

### LINKED ISSUE #6: [BUG]: no json header present for adding segments post request
### Description of the bug

I wanted to submit segments, however I got a 400 Bad Request. I then modified the client.py Code to show the error by printing `response.text` in line 391. => "No valid videoID, userID field(s) provided." But these were both valid.
After some searching: You need to send a header that declares you're sending json.

```
headers = {'Content-type': 'application/json'}
requests.post(url, data=json.dumps(body), headers=headers)
```

Or alternative you can use the `json` keyword instead of `data`

Maybe it would be a good idea to append the request.text to the raised error message so the suer knows what exactly is the problem

### Steps To Reproduce

```
import sponsorblock
client = sponsorblock.Client(user_id="my ID from the settings menu")
client.add_skip_segments(
        "https://www.youtube.com/watch?v=XYZ",
        segment=sponsorblock.Segment(category="intro", start=0, end=6.845000)
    )
```
=> 400 Bad Request

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SVNKoch**
the json keyword adds a header that the content is of type Json

Closes #6 

## 📑 Description

Uses the jeson keyword for sending the request.

### CODE REVIEW

**Comment by SVNKoch** [comment]
haha guess Restyle doesn't like your code style xD

**Comment by wasi-master** [comment]
Lol yeah, I've merged it from my phone, It'll be public when I go into my PC tomorrow :)

**Comment by SVNKoch** [comment]
:+1:  just noticed there are 2 more functions using data instead of json :sweat_smile:

**Comment by wasi-master** [comment]
I'll fix these thank you @SVNKoch 

I think I'll just use a global headers inside the session

**Pull request merged**
